server_names = ['quad9-doh-a', 'quad9-doh-b']

listen_addresses = ['127.0.0.1:53']
max_clients = 250
user_name = 'nobody'

ipv4_servers = true
ipv6_servers = false

dnscrypt_servers = false
doh_servers = true

require_dnssec = true
require_nolog = true
require_nofilter = false

force_tcp = false
timeout = 5000
keepalive = 30
lb_strategy = 'p2'

log_level = 2
use_syslog = false

tls_disable_session_tickets = true
ignore_system_dns = true

netprobe_timeout = 30
netprobe_address = '9.9.9.9:443'

block_ipv6 = true
block_unqualified = true
block_undelegated = true

cache = true
cache_size = 4096
cache_min_ttl = 600
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600

[static.'quad9-doh-a']
stamp = 'sdns://AgMAAAAAAAAABzkuOS45LjkgsBkgdEu7dsmrBT4B4Ht-BQ5HPSD3n3vqQ1-v5DydJC8SZG5zOS5xdWFkOS5uZXQ6NDQzCi9kbnMtcXVlcnk'

[static.'quad9-doh-b']
stamp = 'sdns://AgMAAAAAAAAADTE0OS4xMTIuMTEyLjkgsBkgdEu7dsmrBT4B4Ht-BQ5HPSD3n3vqQ1-v5DydJC8SZG5zOS5xdWFkOS5uZXQ6NDQzCi9kbnMtcXVlcnk'
